[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
puppet = "2BA4FZ7AuZtm6uYhXqmgmEVG3SHFjFxiC6VyGp8St5UM"
puppet-master = "HSCMBajcTi3qFda9S3ao6AepjXefdn3MDhMkiY3fP8mf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
